import { FinancialProfile, FinancialMetrics, FinancialHealthScoreBreakdown, DecisionEngineResult, OptimizationResult, WhatIfResult, MonteCarloResult, RiskAssessment, ChatResponse, MarketKnowledge, Goal } from '../types';
import { ClientFinancialEngine, DEFAULT_DEMO_PROFILE } from './clientEngine';

const API_BASE = import.meta.env.VITE_API_URL || '/api';
const STORAGE_KEY = 'finarch_ai_profile';

export class ApiService {
  private static isBackendAvailable: boolean | null = null;
  static async checkBackend(): Promise<boolean> { try { const res = await fetch(`${API_BASE}/health`, { signal: AbortSignal.timeout(1200) }); this.isBackendAvailable = res.ok; return res.ok; } catch { this.isBackendAvailable = false; return false; } }
  static getLocalProfile(): FinancialProfile { try { const saved = localStorage.getItem(STORAGE_KEY); if (saved) return JSON.parse(saved); } catch { /* fallback */ } return DEFAULT_DEMO_PROFILE; }
  static saveLocalProfile(profile: FinancialProfile): void { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(profile)); } catch { /* ignore storage failure */ } }
  static async getProfile(): Promise<FinancialProfile> { if (this.isBackendAvailable !== false) { try { const res = await fetch(`${API_BASE}/profile`, { signal: AbortSignal.timeout(1500) }); if (res.ok) { const data = await res.json(); this.saveLocalProfile(data); this.isBackendAvailable = true; return data; } } catch { this.isBackendAvailable = false; } } return this.getLocalProfile(); }
  static async updateProfile(profile: FinancialProfile): Promise<FinancialProfile> { this.saveLocalProfile(profile); if (this.isBackendAvailable) { try { const res = await fetch(`${API_BASE}/profile`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(profile), signal: AbortSignal.timeout(2000) }); if (res.ok) return await res.json(); } catch { this.isBackendAvailable = false; } } return profile; }
  static async resetToDemo(): Promise<FinancialProfile> { this.saveLocalProfile(DEFAULT_DEMO_PROFILE); if (this.isBackendAvailable) { try { const res = await fetch(`${API_BASE}/profile/reset-demo`, { method: 'POST', signal: AbortSignal.timeout(2000) }); if (res.ok) return await res.json(); } catch { this.isBackendAvailable = false; } } return DEFAULT_DEMO_PROFILE; }
  static async getFinancialTwin(): Promise<{profile: FinancialProfile; metrics: FinancialMetrics; health_score: FinancialHealthScoreBreakdown; risk_assessment: RiskAssessment; portfolio: any}> { const profile=await this.getProfile(); const metrics=ClientFinancialEngine.calculateMetrics(profile); const health_score=ClientFinancialEngine.calculateHealthScore(profile); const risk_assessment=ClientFinancialEngine.assessRisk(profile); const portfolio={allocations:[{name:'Equity & Stocks',value:profile.stocks_equity+profile.mutual_funds*.7,percentage:metrics.equity_allocation_pct,color:'#06b6d4'},{name:'Debt & Fixed Income',value:profile.fixed_deposits+profile.mutual_funds*.3,percentage:metrics.debt_allocation_pct,color:'#10b981'},{name:'Gold & Commodities',value:profile.gold_assets,percentage:metrics.gold_allocation_pct,color:'#f59e0b'},{name:'Cash & Liquid',value:metrics.total_liquid_cash,percentage:metrics.cash_allocation_pct,color:'#6366f1'}]}; return {profile,metrics,health_score,risk_assessment,portfolio}; }
  static async analyzeDecision(amount:number=10000):Promise<DecisionEngineResult>{const profile=await this.getProfile(); if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/analyze?amount=${amount}`,{method:'POST',signal:AbortSignal.timeout(2000)}); if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}} return ClientFinancialEngine.evaluateDecision(profile,amount);}
  static async optimizeOpportunity(amount:number=50000,weights={expected_return:.25,risk_reduction:.20,liquidity:.20,debt_payoff:.20,goal_alignment:.15}):Promise<OptimizationResult>{const profile=await this.getProfile(); if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/optimize`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,...weights}),signal:AbortSignal.timeout(2000)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}} return ClientFinancialEngine.optimizeOpportunity(profile,amount,weights);}
  static async simulateWhatIf(params:any):Promise<WhatIfResult>{const profile=await this.getProfile(); if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/simulate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(params),signal:AbortSignal.timeout(2000)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}}return ClientFinancialEngine.simulateWhatIf(profile,params);}
  static async runMonteCarlo(initialWealth=650000,monthlySavings=33000,years=10,numSimulations=1000,expectedReturnPct=12,volatilityPct=15,targetGoal=7500000):Promise<MonteCarloResult>{if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/simulate/monte-carlo`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initial_wealth:initialWealth,monthly_savings:monthlySavings,years,num_simulations:numSimulations,expected_return_pct:expectedReturnPct,annual_volatility_pct:volatilityPct,target_goal_wealth:targetGoal}),signal:AbortSignal.timeout(3500)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}}return ClientFinancialEngine.runMonteCarlo(initialWealth,monthlySavings,years,numSimulations,expectedReturnPct,volatilityPct,targetGoal);}
  static async askAdvisor(message:string,apiKey?:string,provider='local'):Promise<ChatResponse>{const profile=await this.getProfile();if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/ai/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,api_key:apiKey,provider}),signal:AbortSignal.timeout(4000)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}}return ClientFinancialEngine.generateAIExplanation(profile,message);}
  static async getMarketKnowledge():Promise<MarketKnowledge>{if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/market/demo`,{signal:AbortSignal.timeout(1500)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}}return ClientFinancialEngine.getMarketKnowledge();}
  static async runIntelligence(snapshot:{symbol?:string;price_change_pct:number;volume_change_pct:number;sentiment_score:number;degraded?:boolean}):Promise<any>{const profile=await this.getProfile();if(this.isBackendAvailable){try{const res=await fetch(`${API_BASE}/intelligence/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(snapshot),signal:AbortSignal.timeout(2500)});if(res.ok)return await res.json();}catch{this.isBackendAvailable=false;}}const module=await import('./marketIntelligence');return module.runMarketIntelligence({...snapshot,symbol:snapshot.symbol??'NIFTY 50',degraded:true},{risk_tolerance:profile.risk_tolerance,investment_horizon_years:profile.investment_horizon_years});}
}
