import React, { useMemo, useState } from 'react';
import { Activity, BrainCircuit, Database, ShieldCheck, Sparkles, WalletCards, Zap } from 'lucide-react';
import { useFinancial } from '../context/FinancialContext';
import { ApiService } from '../services/api';
import { runMarketIntelligence } from '../services/marketIntelligence';

const demoSnapshot = { symbol: 'NIFTY 50', price_change_pct: 3.4, volume_change_pct: 27, sentiment_score: 0.42, forward_return_pct: 4.1, degraded: true, source: 'Embedded deterministic market snapshot' };
const SESSION_KEY = 'finarch_intelligence_sessions';

type SessionMetric = { session_id:string; timestamp:string; signal_accuracy_pct:number; agent_latency_ms:number; portfolio_concentration_pct:number; recommendation:string; user_decision:string; agent_outputs:any[]; degraded_mode:boolean };

function concentration(profile:any){
  const keys=['stocks_equity','mutual_funds','fixed_deposits','gold_assets','cash_savings','emergency_fund'];
  const values=keys.map(k=>Number(profile?.[k]??0)).filter(v=>Number.isFinite(v)&&v>0); const total=values.reduce((a,b)=>a+b,0);
  return total?Math.round(Math.max(...values)/total*1000)/10:0;
}
function loadSessions():SessionMetric[]{try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'[]')}catch{return[]}}

export const IntelligencePage:React.FC=()=>{
  const {profile}=useFinancial();
  const [result,setResult]=useState<any>(()=>runMarketIntelligence(demoSnapshot,{risk_tolerance:profile.risk_tolerance,investment_horizon_years:profile.investment_horizon_years}));
  const [running,setRunning]=useState(false); const [status,setStatus]=useState('DEGRADED / OFFLINE-SAFE');
  const [session,setSession]=useState<SessionMetric|null>(null); const [sessions,setSessions]=useState<SessionMetric[]>(loadSessions);
  const portfolioConcentration=useMemo(()=>concentration(profile),[profile]);
  const saveSession=(data:any,latency:number)=>{
    const momentum=data.agents.find((a:any)=>String(a.agent).includes('momentum'));
    const accuracy=momentum?.signal==='BULLISH'?(demoSnapshot.forward_return_pct>0?100:0):(demoSnapshot.forward_return_pct<0?100:50);
    const item:SessionMetric={session_id:`INT-${Date.now()}`,timestamp:new Date().toISOString(),signal_accuracy_pct:accuracy,agent_latency_ms:latency,portfolio_concentration_pct:portfolioConcentration,recommendation:data.synthesis.recommendation,user_decision:'not recorded',agent_outputs:data.agents,degraded_mode:Boolean(data.degraded_mode)};
    const next=[item,...loadSessions()].slice(0,20); try{localStorage.setItem(SESSION_KEY,JSON.stringify(next))}catch{} setSession(item);setSessions(next);
  };
  const recordDecision=(decision:string)=>{if(!session)return;const updated={...session,user_decision:decision};const next=loadSessions().map(s=>s.session_id===session.session_id?updated:s);try{localStorage.setItem(SESSION_KEY,JSON.stringify(next))}catch{}setSession(updated);setSessions(next)};
  const run=async()=>{setRunning(true);const started=performance.now();try{const data=await ApiService.runIntelligence(demoSnapshot);setResult(data);setStatus(data.degraded_mode?'DEGRADED DATA':'ONLINE');saveSession(data,Math.max(1,Math.round(performance.now()-started)))}catch{const data=runMarketIntelligence(demoSnapshot,{risk_tolerance:profile.risk_tolerance,investment_horizon_years:profile.investment_horizon_years});setResult(data);setStatus('DEGRADED / OFFLINE-SAFE');saveSession(data,Math.max(1,Math.round(performance.now()-started)))}finally{setRunning(false)}};
  const evidence=result.retrieved_evidence||[];
  return <div className="space-y-6 animate-in fade-in duration-300">
    <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 pb-4 border-b border-white/[0.08]"><div><span className="tech-badge bg-cyan-500/10 text-cyan-300 border border-cyan-500/30">PS SPRINT 1 • AUTONOMOUS INTELLIGENCE</span><h1 className="text-3xl font-extrabold text-white font-mono mt-2">MARKET INTELLIGENCE TRACE</h1><p className="text-sm text-slate-400 mt-2 max-w-3xl">Raw market data → three independent specialist agents → semantic retrieval → profile weighting → explainable synthesis.</p></div><button onClick={run} disabled={running} className="px-5 py-3 rounded-md bg-mint-500 text-obsidian-950 font-mono font-bold text-xs flex items-center gap-2 disabled:opacity-60"><Zap className="w-4 h-4"/>{running?'RUNNING PIPELINE…':'RUN INTELLIGENCE'}</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <div className="fin-panel p-4"><span className="tech-label text-slate-500">SIGNAL ACCURACY</span><div className="text-lg font-mono font-bold text-white mt-1">{session?`${session.signal_accuracy_pct}%`:'—'}</div><div className="text-[11px] text-slate-500 mt-1">Measured vs supplied forward return</div></div>
      <div className="fin-panel p-4"><span className="tech-label text-slate-500">AGENT LATENCY</span><div className="text-lg font-mono font-bold text-white mt-1">{session?`${session.agent_latency_ms} ms`:'—'}</div><div className="text-[11px] text-slate-500 mt-1">Measured per completed run</div></div>
      <div className="fin-panel p-4"><span className="tech-label text-slate-500">PORTFOLIO CONCENTRATION</span><div className="text-lg font-mono font-bold text-white mt-1">{portfolioConcentration}%</div><div className="text-[11px] text-slate-500 mt-1">Largest stored asset bucket</div></div>
      <div className="fin-panel p-4"><span className="tech-label text-slate-500">DATA STATUS</span><div className="text-lg font-mono font-bold text-white mt-1">{status}</div><div className="text-[11px] text-slate-500 mt-1">Fallback explicitly labeled</div></div>
    </div>
    <div className="fin-panel p-5"><div className="flex items-center gap-2 mb-4"><Activity className="w-4 h-4 text-cyan-400"/><h2 className="font-mono font-bold text-white">RAW MARKET SIGNALS</h2></div><div className="grid grid-cols-3 gap-4"><div><span className="tech-label text-slate-500">PRICE / MOMENTUM</span><div className="text-2xl font-mono text-white mt-1">+{demoSnapshot.price_change_pct}%</div></div><div><span className="tech-label text-slate-500">VOLUME ANOMALY</span><div className="text-2xl font-mono text-white mt-1">+{demoSnapshot.volume_change_pct}%</div></div><div><span className="tech-label text-slate-500">SENTIMENT</span><div className="text-2xl font-mono text-white mt-1">{demoSnapshot.sentiment_score.toFixed(2)}</div></div></div><div className="mt-4 text-xs text-amber-300/90 bg-amber-500/10 border border-amber-500/20 rounded p-3">⚠ {demoSnapshot.source}. Forward return is used only to make the accuracy metric measurable; it is not presented as a live prediction.</div></div>
    <div className="grid lg:grid-cols-3 gap-5">{(result.agents||[]).map((a:any)=><div key={a.agent} className="fin-panel p-5"><div className="flex justify-between"><span className="tech-label text-cyan-300">{String(a.agent).replaceAll('_',' ').toUpperCase()}</span><BrainCircuit className="w-4 h-4 text-slate-500"/></div><div className="text-xl font-mono font-bold text-white mt-3">{a.signal}</div><div className="text-xs text-slate-400 mt-2">{a.rationale}</div><div className="mt-4 flex justify-between text-[11px] font-mono"><span className="text-slate-500">CONFIDENCE</span><span className="text-mint-300">{Number(a.confidence).toFixed(1)}%</span></div><div className="h-1.5 bg-white/10 rounded mt-1"><div className="h-full bg-mint-400 rounded" style={{width:`${a.confidence}%`}}/></div><div className="mt-3 text-[10px] text-slate-500">Grounding: {(a.evidence_ids||[]).join(' • ')||'local corpus'}</div></div>)}</div>
    <div className="grid lg:grid-cols-5 gap-5"><div className="lg:col-span-3 fin-panel p-5"><div className="flex items-center gap-2"><Sparkles className="w-4 h-4 text-mint-400"/><h2 className="font-mono font-bold text-white">SYNTHESIS LAYER</h2></div><div className="grid grid-cols-2 gap-4 mt-5"><div><span className="tech-label text-slate-500">FINAL ACTION</span><div className="text-3xl font-mono font-black text-mint-300 mt-1">{result.synthesis?.recommendation}</div></div><div><span className="tech-label text-slate-500">DECISION SCORE</span><div className="text-3xl font-mono font-black text-white mt-1">{result.synthesis?.decision_score}/100</div></div></div><p className="text-sm text-slate-300 mt-5">{result.synthesis?.reasoning}</p><p className="text-xs text-cyan-300 mt-3">{result.synthesis?.profile_effect}</p><div className="flex gap-2 mt-5"><button onClick={()=>recordDecision('accepted')} disabled={!session} className="px-3 py-2 rounded border border-mint-500/30 text-mint-300 text-xs font-mono disabled:opacity-40">ACCEPT RECOMMENDATION</button><button onClick={()=>recordDecision('rejected')} disabled={!session} className="px-3 py-2 rounded border border-white/10 text-slate-300 text-xs font-mono disabled:opacity-40">REJECT</button></div></div><div className="fin-panel p-5"><ShieldCheck className="w-5 h-5 text-mint-400"/><span className="tech-label text-slate-500 block mt-3">PROFILE EFFECT</span><div className="text-white font-mono font-bold mt-1">{profile.risk_tolerance.toUpperCase()}</div><div className="text-xs text-slate-400 mt-2">{profile.investment_horizon_years}-year horizon</div><div className="text-xs text-mint-300 mt-4">Confidence: {result.synthesis?.confidence}%</div></div></div>
    <div className="fin-panel p-5"><div className="flex items-center gap-2 mb-4"><WalletCards className="w-4 h-4 text-cyan-400"/><h2 className="font-mono font-bold text-white">CURRENT PORTFOLIO / WATCHLIST STATE</h2></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['EQUITY','stocks_equity'],['MUTUAL FUNDS','mutual_funds'],['FIXED INCOME','fixed_deposits'],['GOLD','gold_assets']].map(([label,key])=><div key={key} className="border border-white/[0.08] rounded p-3"><span className="tech-label text-slate-500">{label}</span><div className="text-white font-mono mt-1">₹{Number((profile as any)[key]??0).toLocaleString('en-IN')}</div></div>)}</div><div className="mt-3 text-xs text-slate-400">Stored profile state feeds suitability. Largest asset-bucket concentration: <b className="text-white">{portfolioConcentration}%</b>.</div></div>
    <div className="fin-panel p-5"><div className="flex items-center gap-2 mb-4"><Database className="w-4 h-4 text-cyan-400"/><h2 className="font-mono font-bold text-white">RETRIEVED EVIDENCE / SOURCE ATTRIBUTION</h2></div><div className="grid md:grid-cols-2 gap-3">{evidence.map((doc:any)=><div key={doc.id} className="border border-white/[0.08] rounded p-3"><div className="text-xs text-cyan-300 font-mono">{doc.id}</div><div className="text-sm text-white font-semibold mt-1">{doc.title}</div><div className="text-xs text-slate-400 mt-1">{doc.text}</div></div>)}</div></div>
    <div className="fin-panel p-5"><div className="tech-label text-slate-500 mb-3">END-TO-END REASONING TRACE</div><div className="flex flex-wrap gap-2 text-xs font-mono">{['RAW MARKET INGESTION','3 PARALLEL AGENTS','SEMANTIC RETRIEVAL','EVIDENCE GROUNDING','PROFILE WEIGHTING','SYNTHESIS','USER RECOMMENDATION'].map((step,i)=><React.Fragment key={step}><span className="px-3 py-2 rounded border border-mint-500/20 bg-mint-500/5 text-mint-300">{i+1}. {step}</span>{i<6&&<span className="text-slate-600 py-2">→</span>}</React.Fragment>)}</div><p className="mt-4 text-xs text-slate-400">Every completed run is persisted in browser storage with timestamp, agent outputs, measurable performance metrics, recommendation, user decision and degraded-mode state.</p></div>
    {sessions.length>0&&<div className="fin-panel p-5"><div className="tech-label text-slate-500 mb-3">SESSION PERFORMANCE LOG</div><div className="overflow-x-auto"><table className="w-full text-xs font-mono"><thead><tr className="text-left text-slate-500 border-b border-white/[0.08]"><th className="py-2">SESSION</th><th>ACCURACY</th><th>LATENCY</th><th>CONCENTRATION</th><th>ACTION</th><th>USER DECISION</th><th>MODE</th></tr></thead><tbody>{sessions.slice(0,8).map(s=><tr key={s.session_id} className="border-b border-white/[0.05] text-slate-300"><td className="py-2">{s.session_id}</td><td>{s.signal_accuracy_pct}%</td><td>{s.agent_latency_ms} ms</td><td>{s.portfolio_concentration_pct}%</td><td>{s.recommendation}</td><td>{s.user_decision}</td><td>{s.degraded_mode?'DEGRADED':'ONLINE'}</td></tr>)}</tbody></table></div></div>}
  </div>;
};
